### PR TITLE
Added Python 3.5+ compatibility fix

### PR DESCRIPTION
**Pull request by frol**
I have tested this fix with Python 2.7 (though it is obvious that it shouldn't be affected by this change), 3.4, 3.5, and 3.6.

Without this fix, I get the following compilation error when I integrate with C++ library:

```
error: invalid conversion from ‘cmpfunc {aka void*}’ to ‘PyAsyncMethods*’
```

Other than that, it seems like PyBindGen works fine with Python 3.5+!

Thank you for this great project!

### CODE REVIEW

**Comment by frol** [comment]
@gjcarneiro Thank you for the blazingly fast merge! Do you have any ETA on when a new release will be cut?

**Comment by gjcarneiro** [comment]
To be honest, I haven't made releases in years, I've been too lazy.  But feel free to use the git version, it's stable.

**Comment by frol** [comment]
Oh, OK... But it is just a single command (`python setup.py sdist upload`), isn't it? Anyways, thank you for making it in the first place!

**Comment by frol** [comment]
I have just found out that there was another fix for this compilation error in https://github.com/gjcarneiro/pybindgen/commit/ec55eb61103a647dc2d6a5ff725b6324e240aa7b, and it might work, but I used the released 0.17.0 version of PyBindGen and this is why I got the error.

**Comment by gjcarneiro** [comment]
Hm, point well taken.   OK, I'll make a release soon, this weekend hopefully.

**Comment by gjcarneiro** [comment]
I pushed out the release, enjoy.

**Comment by frol** [comment]
@gjcarneiro Thank you!
