### ISSUE TITLE
gccxml_configuration_t is deprecated

### ISSUE THREAD

**Issue by cls** [gjcarneiro/pybindgen#9]
`pygccxml.parser.gccxml_configuration_t` is used in `pybindgen.gccxmlparser`, but this is deprecated as of pygccxml-1.7, and it will be removed as of pygccxml-1.9. It should be replaced with `pygccxml.parser.xml_generator_configuration_t` (apparently renamed to reflect their now preferring CastXML). However, a more subtle arrangement may be necessary if pybindgen is to maintain compatibility with pygccxml-1.6 and earlier.

**Comment by lorenzleutgeb** [comment]
Yep, and this makes `pybindgen` unusable for me (`gen.py` is [this snippet](https://pybindgen.readthedocs.io/en/latest/tutorial/#header-file-scanning-with-py-gccxml)):

```
Traceback (most recent call last):
  File "./gen.py", line 18, in <module>
    my_module_gen()
  File "./gen.py", line 11, in my_module_gen
    module = module_parser.parse([sys.argv[1]])
  File "/home/lorenz/.local/lib/python3.7/site-packages/pybindgen/gccxmlparser.py", line 599, in parse
    pygen_classifier, gccxml_options)
  File "/home/lorenz/.local/lib/python3.7/site-packages/pybindgen/gccxmlparser.py", line 694, in parse_init
    self.gccxml_config = parser.gccxml_configuration_t(**gccxml_options)
AttributeError: module 'pygccxml.parser' has no attribute 'gccxml_configuration_t'
```

**Comment by gjcarneiro** [comment]
Don't use `pybindgen.gccxmlparser`, just please switch to `pybindgen.castxmlparser`:  I tried it  today and it seems to work fine.

**Comment by ricardobiundo** [comment]
> 
> 
> Don't use `pybindgen.gccxmlparser`, just please switch to `pybindgen.castxmlparser`: I tried it today and it seems to work fine.

Thank you man. It works using python2.7
